import { ToastProvider } from "@/components/Toast";
import "./globals.css";
import { Inter } from "next/font/google";
import Toaster from "@/components/Toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`bg-white text-slate-900 antialiased light',
    ${inter.className}`}
    >
      <body className="min-h-screen pt-12 bg-slate-50 antialiased">
        <ToastProvider>
          <div className="container max-w-7xl mx-auto h-full pt-12">
            {children}
          </div>
          <Toaster />
        </ToastProvider>
      </body>
    </html>
  );
}
